# Generated by Django 4.0.4 on 2022-12-12 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='sku')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'В наличии'), (2, 'Под заказ'), (3, 'Ожидается поступление'), (4, 'Нет в наличии'), (5, 'Не производится')], null=True, verbose_name='status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='image')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
    ]
