# Generated by Django 4.0.4 on 2022-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
